### PR TITLE
Updated Dirt textures to moon theme 

### PR DESCRIPTION
**Pull request by CrimsonBlack**
Changed Grass, Dirt, Snow, and sand textures to look like moon dirt.

### CODE REVIEW

**Comment by rhartlage10** [comment]
The bottom rightmost block in the textures.png should remain the white cloud block since the gray block makes the "stars" appear much dimmer. Also, maybe a little more contrast between the blocks that were dirt and sand would be nice since the grays appear to be almost the same color in the game.

**Review by rhartlage10 — CHANGES_REQUESTED** [review]
The bottom rightmost block should remain the white cloud block since the gray block makes the "stars" appear much dimmer. Also, maybe a little more contrast between the blocks that were dirt and sand would be nice since the grays appear to be almost the same color in the game.

**Comment by CrimsonBlack** [comment]
Updated sand and stone textures to provide better contrast. also reverted cloud texture back to normal.

**Review by rhartlage10 — APPROVED** [review]
Thanks for making those changes. It looks good!

**Pull request merged**
