### PR TITLE
Fix the mouse sensitivity to close issue #14

### PR DESCRIPTION
**Pull request by CrimsonBlack**
Let me know how well the mouse works for you. my machine is lagging too much for me to figure how good it is.

### CODE REVIEW

**Review by ronnigschwind — COMMENTED** [review]
It's still pretty buggy for me. The view locks straight up into the sky or down at the ground for.

**Comment by CrimsonBlack** [comment]
try and see if that fixed it.

**Review by ronnigschwind — COMMENTED** [review]
The mouse sensitivity seems slightly improved, but it's still buggy.

**Comment by CrimsonBlack** [comment]
Sorry but I think thats the best I can manage to get it

**Pull request merged**
